import { Component, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-report-issue',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './report-issue.html',
  styleUrl: './report-issue.css'
})
export class ReportIssueComponent {
  issueData = {
    issue_type: '',
    description: '',
    related_user_id: ''
  };
  
  selectedFile: File | null = null;
  isSubmitting: boolean = false;
  successMessage: string = '';
  errorMessage: string = '';

  // Options matching your wireframe
  issueTypes = ['Plumbing', 'Payment Error', 'Inappropriate content', 'Harassment', 'Spam', 'Bug', 'Other'];

  constructor(private http: HttpClient, private cdr: ChangeDetectorRef) {}

  onFileSelected(event: any) {
    this.selectedFile = event.target.files[0];
  }

  submitReport() {
    this.errorMessage = '';
    
    // EF1: Manual check before sending
    if (!this.issueData.issue_type || !this.issueData.description) {
      this.errorMessage = 'Please complete all required fields before submitting.';
      return;
    }

    this.isSubmitting = true;

    // Use FormData to handle the file upload
    const formData = new FormData();
    formData.append('issue_type', this.issueData.issue_type);
    formData.append('description', this.issueData.description);
    
    if (this.issueData.related_user_id) {
      formData.append('related_user_id', this.issueData.related_user_id);
    }
    if (this.selectedFile) {
      formData.append('attachment', this.selectedFile);
    }

    // Our Interceptor will handle the token!
    this.http.post('http://localhost:8000/api/reports', formData).subscribe({
      next: (response: any) => {
        this.isSubmitting = false;
        // Show success and the Reference ID generated by Laravel
        this.successMessage = `Report submitted successfully! Your Reference ID is: ${response.reference_id}`;
        
        // Reset form
        this.issueData = { issue_type: '', description: '', related_user_id: '' };
        this.selectedFile = null;
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.isSubmitting = false;
        // EF2: File upload failed or other error
        this.errorMessage = err.error?.message || 'Submission failed. Please try again or submit without the file.';
        this.cdr.detectChanges();
      }
    });
  }
}